server.port=25561
spring.application.name=HulpApplication
spring.security.user.name=admin
spring.security.user.password=hulp_welfen_rv

# H2 Einstellungen
spring.datasource.url=jdbc:h2:file:./data/chatdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Erstellt die Tabellen automatisch basierend auf deinen Java-Klassen
spring.jpa.hibernate.ddl-auto=update

# H2 Konsole (zum Reinschauen unter localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console