server.port=25561
spring.application.name=HulpApplication
spring.security.user.name=admin
spring.security.user.password=hulp_welfen_rv

# H2 Einstellungen
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.url=jdbc:h2:file:./data/chatdb;CIPHER=AES;PASSWORD=384zht83th38tfgh38tgu084gu4e8rihgb4h3huje4hjr5ehruh8u7g0ti sa_passwort
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Erstellt die Tabellen automatisch basierend auf deinen Java-Klassen
spring.jpa.hibernate.ddl-auto=update

# H2 Konsole (zum Reinschauen unter localhost:8080/h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

logging.level.welfen_rv.hulp=DEBUG
logging.file.name=logs/hulp-app.log
# Limitiert die Log-Datei auf 10MB und bewahrt maximal 7 Tage alte Logs auf
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7